"
I store metadata for this package. These meta data are used by other tools such as the SmalllintManifestChecker and the critics Browser
"
Class {
	#name : #ManifestPetitParserPEG,
	#superclass : #PackageManifest,
	#category : #'PetitParser2-PEG'
}

{ #category : #'meta-data' }
ManifestPetitParserPEG class >> description [ ^ 'This package provides the PEG ASCII syntax definition accompanied by a compiler and a parser to PetitParser2.'
]
