SystemOrganization addCategory: #'PetitParser2-RewriteEngine'!
SystemOrganization addCategory: 'PetitParser2-RewriteEngine-Core'!
SystemOrganization addCategory: 'PetitParser2-RewriteEngine-Examples'!
SystemOrganization addCategory: 'PetitParser2-RewriteEngine-Nodes'!
SystemOrganization addCategory: 'PetitParser2-RewriteEngine-SmaCC'!
SystemOrganization addCategory: 'PetitParser2-RewriteEngine-Strategies'!
