SystemOrganization addCategory: #'PetitParser2-Tests'!
SystemOrganization addCategory: 'PetitParser2-Tests-Analysis'!
SystemOrganization addCategory: 'PetitParser2-Tests-BufferStream'!
SystemOrganization addCategory: 'PetitParser2-Tests-Core'!
SystemOrganization addCategory: 'PetitParser2-Tests-Examples'!
SystemOrganization addCategory: 'PetitParser2-Tests-Interpretation'!
SystemOrganization addCategory: 'PetitParser2-Tests-Parsers'!
SystemOrganization addCategory: 'PetitParser2-Tests-Strategies'!
